import Vue from "vue";
import {
    Button,
    Cell,
    CellGroup,
    Col,
    Divider,
    Grid,
    GridItem,
    Icon,
    Image as VanImage,
    Lazyload,
    List,
    NavBar,
    Overlay,
    Popup,
    Row,
    Swipe,
    SwipeItem,
    Tab,
    Tabbar,
    TabbarItem,
    Tabs,
    Toast,
    Tag,
    Empty,
    Loading,
    Pagination,
    ActionSheet,
    DropdownMenu,
    DropdownItem,
    Notify
} from 'vant';

Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Notify);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Overlay);
Vue.use(Button);
Vue.use(Col);
Vue.use(Row);
Vue.use(NavBar);
Vue.use(Icon);
Vue.use(CellGroup);
Vue.use(Divider);
Vue.use(Lazyload);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Popup);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(List);
Vue.use(VanImage);
Vue.use(Cell);
Vue.use(Toast);
Vue.use(Tag);
Vue.use(Loading);
Vue.use(Pagination);
Vue.use(ActionSheet);
Vue.use(Empty);
Vue.use(Divider);
